create a MBR function
pfeinsper/drone-swarm-search pull request #213
Opened 2024-04-18 03:57 UTC by Pedro2712

2024-04-18 12:35 UTC, renatex333 requested changes

2024-04-18 12:35 UTC, renatex333 commented on DSSE/environment/simulation/particle_sim.py
Hello, Pedro! How are you doing?

I'm here to give some suggestions on your new code.

1. I suggest using type hints in your functions to help readers understand quickly the data that should come in and out, for example:

`def calculate_bounding_rectangle(coordinates: list[tuples[float]]) -> tuple[float]:`

2. In the function `calculate_bounding_rectangle` I would suggest avoiding for loops in order to get the min and max values of the latitude and longitude. Assuming that the `coordinates` variable is a list of tuples, you could get the min and max with the following:

```
latitudes, longitudes = zip(*coordinates)

min_lat, max_lat = min(latitudes), max(latitudes)

min_lon, max_lon = min(longitudes), max(longitudes)
```

3. Just as a code convention according to Clean Code, I suggest that you write code like a book, writing the functions that make the calls before writing the functions that are called.

2024-04-18 18:50 UTC, Pedro2712 commented on DSSE/environment/simulation/particle_sim.py
fuck you

2024-04-18 18:51 UTC, renatex333 approved these changes

2024-04-18 23:09 UTC, renatex333 approved these changes
Nice

2024-04-24 14:38 UTC, JorasOliveira approved these changes

2024-05-01 23:07 UTC, closed without merging