Add: Algorithms and Coverage Env Docs
pfeinsper/drone-swarm-search pull request #240
Opened 2024-05-01 23:55 UTC by Pedro2712

2024-05-02 16:55 UTC, renatex333 commented on docs/.vitepress/config.mts
> +        label: 'Português (Embreve)',
```suggestion
        label: 'Português (Em breve)',
```

2024-05-02 17:03 UTC, renatex333 approved these changes

2024-05-06 01:11 UTC, RicardoRibeiroRodrigues requested changes

2024-05-06 01:11 UTC, RicardoRibeiroRodrigues commented on DSSE/environment/env.py
> +        # Prob m"DSSE/tests/matrix.npy"atrix
Por que esse comentário ??

2024-05-06 01:11 UTC, RicardoRibeiroRodrigues commented on basic_coverage.py
Não acredito que seja que fique bom o exemplo carregando de um arquivo pronto, fica melhor para exemplificar a geração da matriz.

2024-05-08 14:25 UTC, renatex333 approved these changes

2024-05-09 16:47 UTC, RicardoRibeiroRodrigues approved these changes

2024-05-09 18:58 UTC, merged