Vitepress docs
pfeinsper/drone-swarm-search pull request #255
Opened 2024-05-23 20:57 UTC by Pedro2712

2024-06-03 15:27 UTC, renatex333 approved these changes

2024-06-11 18:34 UTC, renatex333 requested changes

2024-06-11 18:34 UTC, renatex333 commented on docs/Documentation/docsAlgorithms.md
> +## Appendix A: Test Configurations
May I suggest:

```suggestion
## Test Configurations
```

I don't think that calling it an Appendix makes sense here. What do you think?

2024-06-11 18:34 UTC, renatex333 commented on docs/.vitepress/config.mts
> +                    { text: 'Appendix A', link: '/Documentation/docsAlgorithms#appendix-a-test-configurations' },
```suggestion
                    { text: 'Test Configurations', link: '/Documentation/docsAlgorithms#appendix-a-test-configurations' },
```

Same suggestion as in "docsAlgorithms.md"

2024-06-14 16:38 UTC, renatex333 approved these changes

2024-06-14 17:59 UTC, RicardoRibeiroRodrigues approved these changes

2024-06-14 17:59 UTC, merged